### ISSUE TITLE
css: break long filenames

### ISSUE THREAD

**Issue by peterdd** [Vestride/fancy-index#20]
so it does not break layout on small displays.

```css
tbody td {word-break:break-all;}
```

example: touch longfilenameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.txt
